services:

  hugo:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '1313:1313'
    volumes:
      - ./app:/usr/src/app
    environment:
      - HUGO_DISABLE_FAST_RENDER=1
