name: Build and Deploy Bakehouse78 App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Step 3: Install dependencies and build
      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      # Step 4: Prepare the build artifact
      - name: Prepare build artifact
        run: |
          mkdir -p build_artifact
          cp -r .next build_artifact/
          cp package.json build_artifact/
          cp -r scripts build_artifact/
          cp appspec.yml build_artifact/
          cd build_artifact
          zip -r ../build.zip .

      # Step 5: Set up AWS credentials with OIDC
      - name: Set up AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: eu-west-2

      # Step 6: Upload artifact to S3
      - name: Upload build artifact to S3
        run: |
          aws s3 cp build.zip s3://bakehouse78-deploybuilds/build.zip
