name: Build Bakehouse78 App and Upload to S3

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Permissions for GitHub OIDC
permissions:
  id-token: write
  contents: read

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app  # Set the working directory to your app directory
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List code
        run: ls -al

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build and export the project
        run: npm run build

      - name: Set up AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: eu-west-2

      - name: Upload build artifact to S3
        run: |
          aws s3 cp ./next s3://bakehouse78-deploybuilds/ --recursive --exclude ".git/*" --exclude "node_modules/*"